[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools"]

[project]
dependencies = [
   "jupyterlab-spellchecker",
   "pytest"
]
name = "deep-learning-curriculum"

version = "0.0.1"
